/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KtCiOREyQRo
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Input } from "@/components/ui/input";
import { CardsGrid } from "./cards-grid";

export function Association() {
  return (
    <div>
      <div className="flex flex-col items-center gap-4 p-4">
        <CardsGrid />
        <div className="w-full max-w-sm">
          <Input placeholder="Ваша ассоциация..." type="text" />
        </div>
      </div>
    </div>
  );
}
