/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KtCiOREyQRo
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Card } from "@/components/ui/card";
import DefaultImage from "@/assets/cards/default.png";

export function CardsGrid() {
  return (
    <div className="flex flex-wrap gap-4 w-full justify-center">
      {[...Array(6)].map((_, i) => (
        <Card
          key={i}
          className="max-w-[300px] aspect-card overflow-hidden hover:border-blue-500 hover:border-2  hover:shadow-lg"
        >
          <img
            alt="Image"
            className="aspect-cover object-center"
            height={2912}
            src={DefaultImage}
            width={1664}
          />
        </Card>
      ))}
    </div>
  );
}
