/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uLSJCc9AcbM
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
export function CreateRoom() {
  return (
    <div className="flex h-screen items-center justify-center bg-[url('/placeholder.svg?height=768&width=1115')] bg-cover">
      <div className="flex flex-col items-center space-y-4">
        <h1 className="text-3xl font-bold text-white">Create a Room</h1>
        <form className="flex flex-col items-center space-y-4">
          <input
            className="w-64 px-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:ring focus:ring-blue-400"
            placeholder="Nickname"
            type="text"
          />
          <button className="w-64 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors">
            Create Room
          </button>
        </form>
      </div>
    </div>
  );
}
