/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/pGDie7I5myO
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import { auth, db } from "@/firebase/firebase-config";
import { playerType } from "@/types";
import { collection } from "firebase/firestore";
import { Route } from "@/routes/room/$roomId.lazy";
import { useAuthState } from "react-firebase-hooks/auth";
import { useCollection } from "react-firebase-hooks/firestore";

export function EndGame() {
  const { roomId } = Route.useParams();
  const [user] = useAuthState(auth);

  const [playersValue] = useCollection(
    collection(db, "rooms", roomId, "players"),
  );
  const players =
    playersValue?.docs.map((doc) => ({
      ...(doc.data() as playerType),
      id: doc.id,
    })) || [];

  return (
    <main className="flex flex-col items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
      <div className="bg-white dark:bg-gray-800 shadow-lg rounded-lg p-8 w-full max-w-3xl">
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold">Imaginarium</h1>
          <div className="flex items-center space-x-2">
            <span className="text-gray-500 dark:text-gray-400">
              Winner: Alice
            </span>
          </div>
        </div>
        <div className="grid grid-cols-4 gap-4">
          <div className="bg-primary text-white rounded-lg p-4 flex flex-col items-center justify-center">
            <div className="w-10 h-10 bg-white rounded-full mb-2" />
            <span className="text-sm font-medium">Alice</span>
            <span className="text-white text-sm">Score: 42</span>
          </div>
          <div className="bg-gray-200 dark:bg-gray-700 rounded-lg p-4 flex flex-col items-center justify-center">
            <div className="w-10 h-10 bg-secondary rounded-full mb-2" />
            <span className="text-sm font-medium">Bob (me)</span>
            <span className="text-gray-500 dark:text-gray-400 text-sm">
              Score: 38
            </span>
          </div>
          <div className="bg-gray-200 dark:bg-gray-700 rounded-lg p-4 flex flex-col items-center justify-center">
            <div className="w-10 h-10 bg-tertiary rounded-full mb-2" />
            <span className="text-sm font-medium">Charlie</span>
            <span className="text-gray-500 dark:text-gray-400 text-sm">
              Score: 29
            </span>
          </div>
          <div className="bg-gray-200 dark:bg-gray-700 rounded-lg p-4 flex flex-col items-center justify-center">
            <div className="w-10 h-10 bg-quaternary rounded-full mb-2" />
            <span className="text-sm font-medium">David</span>
            <span className="text-gray-500 dark:text-gray-400 text-sm">
              Score: 22
            </span>
          </div>
        </div>
        <div className="flex justify-center mt-8">
          <Button>New Game</Button>
        </div>
      </div>
    </main>
  );
}
