/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KMREU1DwqY9
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { auth, db } from "@/firebase/firebase-config";
import { Route } from "@/routes/room/$roomId.lazy";
import { playerType } from "@/types";
import { collection, doc } from "firebase/firestore";
import { useAuthState } from "react-firebase-hooks/auth";
import { useCollection, useDocument } from "react-firebase-hooks/firestore";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function GameHeader() {
  const { roomId } = Route.useParams();
  const [user] = useAuthState(auth);

  const [playersValue] = useCollection(
    collection(db, "rooms", roomId, "players"),
  );
  const players =
    playersValue?.docs.map((doc) => ({
      ...(doc.data() as playerType),
      id: doc.id,
    })) || [];

  const [roomValue] = useDocument(doc(db, "rooms", roomId));

  console.log(roomValue?.data());

  const activePlayer = players.find(
    (player) => player.id === roomValue?.data()?.activePlayer,
  );

  console.log(activePlayer);

  return (
    <div className="bg-white dark:bg-gray-800 shadow-lg rounded-lg p-8 w-full">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">Imaginarium</h1>
        <div className="flex items-center space-x-2">
          <span className="text-gray-500 dark:text-gray-400">
            It's{"\n"}
            <span className="font-bold text-primary">
              {activePlayer?.nickname}'s
            </span>
            {"\n"}turn{"\n"}
          </span>
          <div className="w-3 h-3 bg-primary rounded-full" />
        </div>
      </div>
      <div className="grid grid-cols-4 gap-4">
        {players.map((player) => (
          <div
            key={player.id}
            className="bg-gray-200 dark:bg-gray-700 rounded-lg p-4 flex flex-col items-center justify-center max-w-sm"
          >
            <div className="w-10 h-10 bg-primary rounded-full mb-2" />
            <span className="text-sm font-medium">
              {player.nickname} {player.id === user?.uid ? "(You)" : ""}
            </span>
            <span className="text-gray-500 dark:text-gray-400 text-sm">
              Score: {player.score || 0}
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}
