/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/uLSJCc9AcbM
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { auth, db } from "@/firebase/firebase-config";
import { doc, setDoc } from "firebase/firestore";
import { SubmitHandler, useForm } from "react-hook-form";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { signInAnonymously } from "firebase/auth";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Route } from "@/routes/room/$roomId";
import { CopyRoomLink } from "./copy-room-link";
import playerQuery from "@/firebase/queries/player";

type Inputs = {
  nickname: string;
};

export function JoinCreatedRoom() {
  const { roomId } = Route.useParams();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Inputs>();

  const onSubmit: SubmitHandler<Inputs> = async (data) => {
    const {
      user: { uid },
    } = await signInAnonymously(auth);
    await setDoc(playerQuery(roomId, uid), {
      user: uid,
      nickname: data.nickname,
    });
  };

  return (
    <div className="flex h-screen items-center justify-center">
      <Card className="w-full max-w-lg">
        <CardHeader>
          <CardTitle className="text-2xl">🎨 Room name: {roomId}</CardTitle>
          <div>
            <CopyRoomLink roomId={roomId} />
          </div>
        </CardHeader>
        <form onSubmit={handleSubmit(onSubmit)}>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="nickname">Nickname</Label>
              <Input
                {...register("nickname")}
                id="nickname"
                placeholder="Enter your nickname"
              />

              {errors.nickname && (
                <p className="text-xs text-red-500 dark:text-red-400">
                  This field is required.
                </p>
              )}
            </div>
            <Button className="w-full">Join</Button>
          </CardContent>
        </form>
      </Card>
    </div>
  );
}
