/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KtCiOREyQRo
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { CardsGrid } from "./cards-grid";
import { SubmitHandler } from "react-hook-form";
import { useDocument } from "react-firebase-hooks/firestore";
import { auth, db } from "@/firebase/firebase-config";
import { playerType, roomType } from "@/types";
import { doc, setDoc } from "firebase/firestore";
import { Route } from "@/routes/room/$roomId.lazy";
import { useAuthState } from "react-firebase-hooks/auth";
import selectCard from "@/firebase/actions/select-card";

export function SelectingCard() {
  const { roomId } = Route.useParams();
  const [user] = useAuthState(auth);

  const [selectedCardValue] = useDocument(
    doc(db, "rooms", roomId, "selectedCards", user?.uid || ""),
  );

  const [roomValue] = useDocument(doc(db, "rooms", roomId));

  const room = roomValue?.data() as roomType;

  const { association } = room || {};

  const { selectedCardId } =
    (selectedCardValue?.data() as
      | {
          selectedCardId: string;
        }
      | undefined) || {};
  undefined;

  function onCardClick(cardId: string) {
    selectCard(cardId, roomId, user?.uid || "");
  }

  return (
    <div>
      <div className="flex flex-col items-center gap-4 p-4">
        {association && (
          <div className="flex flex-col items-center gap-4 p-4">
            <div className="flex flex-col items-center gap-4 p-4">
              Association: {association}
            </div>
          </div>
        )}
        <CardsGrid selectedCardId={selectedCardId} onCardClick={onCardClick} />
      </div>
    </div>
  );
}
