/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mnQoBIpeeHo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function temp() {
  return (
    <Card className="w-full max-w-lg">
      <CardHeader>
        <CardTitle className="text-2xl">Create a Game Room</CardTitle>
        <CardDescription>Enter your nickname to create a game room</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="nickname">Nickname</Label>
          <Input id="nickname" placeholder="Enter your nickname" />
        </div>
        <Button className="w-full">Create</Button>
      </CardContent>
    </Card>
  )
}
